name: Dart

on:
  push:
    branches: 
      - main

jobs:
  build-and-test: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # The flutter action needs java so include it
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    # Include the flutter action
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'  
    # Get flutter packages
    - run: flutter pub get
    # Change app icon
    - run: flutter pub run flutter_launcher_icons:main
    # Build :D 
    - run: flutter build apk --split-per-abi

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk

    - name: Download APK
      uses: actions/download-artifact@v2
      with:
        name: app-release
        path: build